### Import numpy library as np

In [2]:
import numpy as np
np.__config__.show()

mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/derdman/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/derdman/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/derdman/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/derdman/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/derdman/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/derdman/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/derdman/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/derdman/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/derdman/anaconda3/lib

### Look up the documentation of the function "linspace" in the numpy library

In [41]:
np.linspace(1,3, num=3)

array([1., 2., 3.])

### Create a Variable X, set it to $\left[\begin{array}{c}1\\2\\3\end{array}\right]$
### Create a Variable Y, set it to  $\left[\begin{array}{c}2\\1\\4\end{array}\right]$
### Print both X and Y
Hint: np.array().reshape()

In [42]:
X=np.array([1,2,3])
X.shape = (3,1)
Y=np.array([2,1,4])
Y.shape = (3,1)
print(X)
print(Y)

[[1]
 [2]
 [3]]
[[2]
 [1]
 [4]]


### Calculate the matrix product of $X^TY$, store it in variable Z. 
### Print Z
Hint: np.ndarray.T and np.ndarray.dot can be chained.

In [43]:
Z=X.T.dot(Y)
print(Z)

[[16]]


### Add 10 to every element of X, and print the result.

In [44]:
print(X+10)

[[11]
 [12]
 [13]]


### Add noise drawn from a normal distribution to every element of Y, and print the result
Hint: use np.random.randn(). Expected result to be the same size as Y

In [45]:
print(Y+np.random.randn(3,1))

[[1.57049044]
 [1.51054121]
 [3.80107883]]


### Re Initialize X as a range of 200 equally spaced numbers between 0 and 2, with shape (200,1). Print last 20 elements of X
Hint: np.linspace() or np.arange()

In [46]:
X=np.linspace(0,2, num=200)
X.shape=(200,1)
print(X[-20:,:])

[[1.80904523]
 [1.81909548]
 [1.82914573]
 [1.83919598]
 [1.84924623]
 [1.85929648]
 [1.86934673]
 [1.87939698]
 [1.88944724]
 [1.89949749]
 [1.90954774]
 [1.91959799]
 [1.92964824]
 [1.93969849]
 [1.94974874]
 [1.95979899]
 [1.96984925]
 [1.9798995 ]
 [1.98994975]
 [2.        ]]


### Find the mean of X and print it
Hint: np.ndarray.mean()

In [47]:
print(X.mean())

1.0000000000000002


###  Make a Variable T and set it equal to the concatenation of a column vector of just ones, and X. Print first 10 elements of T, and the count of the elements you printed
Hint: np.hstack() and np.ones()
Expected Output: $$\left[\begin{array}{c}1&t_1\\1&t_2\\.&.\\.&.\\.&.\\.&.\\1&t_{10}\end{array}\right]$$

### Re-initialize Y as: $$Y = T \left[\begin{array}{c}2.7\\9.5 \end{array}\right]+3.2 \epsilon$$
<br> 
where $\epsilon$ is Noise, with the same dimensions as T minus one column, sampled from a normal distribution
### Print first 20 elements of Y

### Import matplotlib.pyplot as plt

In [2]:
import matplotlib.pyplot as plt

### Create a scatter plot of second column of T and Y. Follow the rest of the specifications
1. Set the size of the figure to (8,9)
2. Create corresponding axis labels with font size 20
3. Set the title to be "Scatter Plot" with font size 24
4. Change the size of all the points to 4
5. Change the color of the points to red

<br>
<br>
Hint: plt...

### Create a Variable F and set it equal to 12 times the second column of Z, without preserving the dimensionality. Print the first 10 values of F.

### Recreate the same scatter plot as earlier. Then, follow these instructions
1. Create a line plot of F with X on the same plot. F on the y-axis, X on the X-axis
2. Set the LineWidth to 4.
3. Set the color of the line to be blue
4. Create a legend indicating that the line is F. Set the font size to 20
5. Set the font of the x and y ticks to be 15