In [1]:
import numpy as np

In [326]:
#Make a small array so that I an actually see the results easily. Two categoricat variables
categorical_data=np.array(["1","4"]*100)
categorical_data=np.hstack((categorical_data.reshape(200,1), np.ones((200,1)),np.array(["1","2"]*100).reshape(200,1)))

In [327]:
#Cast array as matrix
categorical_data=np.matrix(categorical_data)

In [328]:
#Sometimes the output wouldn't change if an error occured, so shuffle sometime to make sure
np.random.shuffle(categorical_data)

In [329]:
#The basics of this code is stack overflow, which I generalized
def get_one_hot(targets):
    #Need the matrix column as a row np array for the following
    targets=np.asarray(targets).reshape(-1)
    #Total number of categories in column
    num_classes=len(np.unique(targets))
    #Create an arry the same length as the column, with the entries correspond to where
    #they appear in the np.unique output, which sorts them.
    indices=np.searchsorted(np.unique(targets),targets)
    #For each index, take the corresponding column out of the identity matrix of size=number of catgories. 
    #So the third entry of the uniques array will make this return [0,0,1,0]. Does so for every index in the indices list
    res = np.eye(num_classes)[indices]
    #return as a column vector
    return res.reshape(len(targets),num_classes)

In [330]:
def mat_ohe(data,cols_to_ohe):
    #Could not entriely avoid for loops, iterate over columns I want to one hot encode
    for i in cols_to_ohe:
        #Actual data in the column passed to one hot encoder, then returned as array of arrays
        ohe_cols=get_one_hot(data[:,i])
        #add the ohe columns to the orifinal matrix
        data=np.hstack((data,ohe_cols))
    #Wait to remove the origianl columns until all columns need have been oh=ne hot ecode, to avoid column numberinf issues
    data=np.delete(data,cols_to_ohe,1)
    #return the data as a number, now that any strings have been removed
    return data.astype(float)
    

In [331]:
categorical_data[:20]

matrix([['1', '1.0', '1'],
        ['1', '1.0', '1'],
        ['1', '1.0', '1'],
        ['1', '1.0', '1'],
        ['4', '1.0', '2'],
        ['1', '1.0', '1'],
        ['4', '1.0', '2'],
        ['1', '1.0', '1'],
        ['1', '1.0', '1'],
        ['4', '1.0', '2'],
        ['1', '1.0', '1'],
        ['1', '1.0', '1'],
        ['1', '1.0', '1'],
        ['4', '1.0', '2'],
        ['1', '1.0', '1'],
        ['1', '1.0', '1'],
        ['4', '1.0', '2'],
        ['4', '1.0', '2'],
        ['4', '1.0', '2'],
        ['4', '1.0', '2']], dtype='<U32')

In [332]:
print(categorical_data[:20])
#It clearly worked for this set
print(mat_ohe(categorical_data,[0,2])[:20])

[['1' '1.0' '1']
 ['1' '1.0' '1']
 ['1' '1.0' '1']
 ['1' '1.0' '1']
 ['4' '1.0' '2']
 ['1' '1.0' '1']
 ['4' '1.0' '2']
 ['1' '1.0' '1']
 ['1' '1.0' '1']
 ['4' '1.0' '2']
 ['1' '1.0' '1']
 ['1' '1.0' '1']
 ['1' '1.0' '1']
 ['4' '1.0' '2']
 ['1' '1.0' '1']
 ['1' '1.0' '1']
 ['4' '1.0' '2']
 ['4' '1.0' '2']
 ['4' '1.0' '2']
 ['4' '1.0' '2']]
[[1. 1. 0. 1. 0.]
 [1. 1. 0. 1. 0.]
 [1. 1. 0. 1. 0.]
 [1. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [1. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 0. 1. 0.]
 [1. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1.]]


In [333]:
categorical_data=np.array([1,2,3,4]*100)
#Columns 2 and 13 should be one hot encoded. Col 2 has 4 categories, and col 13 has 2, so I should gain 4 columns after ohe
categorical_data=np.hstack((np.random.randint(0,100,size=(400,1)),categorical_data.reshape(400,1), np.random.randint(0,100,size=(400,10)),np.array(["fee","fi"]*200).reshape(400,1),np.random.randint(50,70,size=(400,5))))

In [334]:
categorical_data

array([['5', '1', '83', ..., '67', '54', '69'],
       ['31', '2', '3', ..., '61', '69', '55'],
       ['36', '3', '67', ..., '69', '67', '65'],
       ...,
       ['31', '2', '61', ..., '56', '50', '61'],
       ['48', '3', '29', ..., '69', '58', '65'],
       ['0', '4', '57', ..., '52', '57', '67']], dtype='<U21')

In [336]:
ohe_larger=mat_ohe(categorical_data,[1,12])

In [346]:
#Third column has moved to first column, and matrix is not all numbers, not strings
categorical_data[:20,2]

array(['83', '3', '67', '96', '63', '71', '21', '1', '59', '1', '82',
       '15', '6', '94', '98', '66', '12', '94', '41', '52'], dtype='<U21')

In [347]:
ohe_larger[:20,1]

array([83.,  3., 67., 96., 63., 71., 21.,  1., 59.,  1., 82., 15.,  6.,
       94., 98., 66., 12., 94., 41., 52.])

In [350]:
#13 has moved to 11
categorical_data[:20,13]

array(['50', '61', '68', '64', '61', '51', '56', '56', '51', '67', '59',
       '61', '59', '52', '60', '50', '58', '56', '50', '52'], dtype='<U21')

In [351]:
ohe_larger[:20,11]

array([50., 61., 68., 64., 61., 51., 56., 56., 51., 67., 59., 61., 59.,
       52., 60., 50., 58., 56., 50., 52.])

In [354]:
#The last 6 columns should be 1s and zeros, with a diagonal of with 4 and one with width 2,
#since the arrays were not sorted. It is, so it seems my one hot encoder works
ohe_larger[:,-6:]

array([[1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0.],
       ...,
       [0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1.]])